version: '3.5'

services:
  webapp:
    container_name: winfadd
    image: aspnetapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "8000:80"
    links:
      - postgres
    environment:
      ASPNETCORE_URLS: http://+ #https://+;http://+

  postgres:
    container_name: db
    image: postgres:latest
    volumes:
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: always
